<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SudokuSolver.Application/SudokuSolver.Application.csproj" />
    <PackageReference Include="Microsoft.Playwright" Version="1.54.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>
</Project>
